#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AndLTCWallet.Resource", IsApplication=true)]

namespace AndLTCWallet
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int listitem = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int QRCode = 2130837506;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070010
			public const int Amount = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int Confirms = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int Fee = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int TransactionID = 2131165201;
			
			// aapt resource value: 0x7f070009
			public const int button1 = 2131165193;
			
			// aapt resource value: 0x7f070006
			public const int editText1 = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int editText2 = 2131165192;
			
			// aapt resource value: 0x7f07000c
			public const int linearLayout1 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int listView1 = 2131165197;
			
			// aapt resource value: 0x7f070014
			public const int menu_newwallet = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int menu_refresh = 2131165203;
			
			// aapt resource value: 0x7f070005
			public const int qrCode = 2131165189;
			
			// aapt resource value: 0x7f07000b
			public const int relativeLayout1 = 2131165195;
			
			// aapt resource value: 0x7f070004
			public const int relativeLayout2 = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int textView1 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int textView2 = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int textView3 = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int textView4 = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int textView5 = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int textView7 = 2131165184;
			
			// aapt resource value: 0x7f07000e
			public const int textView8 = 2131165198;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int ActionItems = 2131099648;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
